# https://github.com/woltapp/wolt-python-package-cookiecutter/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/test.yml
# https://joaodlf.com/using-poetry-in-github-actions-the-easy-way.html
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run pytest
